#!/bin/bash

#SBATCH --partition=orion
#SBATCH --qos=windfall
#SBATCH --job-name=NeverWorld2_neeraja
#SBATCH --mail-user=neerajab@princeton.edu
#SBATCH --mail-type=ALL
#SBATCH --time=06:00:00
#SBATCH --nodes=40
#SBATCH --ntasks=800
#SBATCH --exclusive
pwd
date
. ../scripts/orion-intel-env

srun ../build/MOM6
date
