#!/bin/bash

### Job Name
#PBS -N neeraja_30000_days

### Project code
#PBS -A UNYU0004
#PBS -l walltime=08:00:00
#PBS -q regular

### Merge output and error files
#PBS -j oe
#PBS -k eod

### Select 2 nodes with 36 CPUs each for a total of 72 MPI processes
#PBS -l select=20:ncpus=36:mpiprocs=36

### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M neerajab@princeton.edu

### Run the executable
mpiexec_mpt  ../build/MOM6
